[platformio]
default_envs = cydusb2
src_dir = esp32_marauder
lib_dir = pio-libs

[env:cydusb2]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000L
monitor_speed = 115200
upload_speed = 460800
lib_ldf_mode = deep+
lib_compat_mode = off
lib_deps =
    libraries/ArduinoJson
    libraries/LinkedList
    libraries/JPEGDecoder
    libraries/MicroNMEA
    libraries/lv_arduino
    libraries/bb_captouch
    libraries/SensorLib
    libraries/EspSoftwareSerial
    libraries/Adafruit_BusIO
    libraries/Adafruit_MAX1704X
    libraries/Adafruit_NeoPixel
    libraries/AsyncTCP
    libraries/ESPAsyncWebServer
    libraries/NimBLE-Arduino
    libraries/TFT_eSPI-CYD/2.8CYD2USB/TFT_eSPI-master
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9341_2_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_INVERSION_OFF=1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DESP32_DMA=1
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DUSE_HSPI_PORT=1
    -DTOUCH_CS=33
    -DTOUCH_MOSI=32
    -DTOUCH_MISO=39
    -DTOUCH_CLK=25
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000
    -Wl,--allow-multiple-definition
